name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: check code style
        run: npx prettier ./src/ --check
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        if: success()
        with:
          to: -4529873179 
          token: ${{ secrets.tg_token }}
          message: Успех
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        if: falure()
        with:
          to: -4529873179 
          token: ${{ secrets.tg_token }}
          message: Успех
      
          
  build:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v4
      - name: Run an one-line script
        run: echo ${{ secrets.tg_token }}
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        if: success()
        with:
          to: -4529873179 
          token: ${{ secrets.tg_token }}
          message: Успех
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          to: -4529873179 
          token: ${{ secrets.tg_token }}
          message: Успех
      
    
